const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8').replace(/\r\n/g, '\n');
function loadModel() {
  const context = { window: {}, document: {}, console };
  vm.createContext(context);
  for (const file of ['theme-registry', 'studio-builder-theme-data', 'studio-builder-presets', 'theme-contrast', 'theme-composer']) {
    vm.runInContext(read('js/' + file + '.js'), context, { filename: file });
  }
  const defaults = {};
  const css = read('css/tokens.css');
  for (const match of css.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) defaults[match[1]] = match[2].trim();
  const data = context.window.DesignSystemStudioBuilderThemeData.initBuilderThemeData();
  const presets = context.window.DesignSystemStudioBuilderPresets.initBuilderPresets(data);
  const composer = context.window.DesignSystemThemeComposer.createComposer(data, defaults, presets.buildColorBundle);
  return { context, defaults, data, composer };
}
function artifacts() {
  const { context, defaults, data, composer } = loadModel();
  const registry = context.window.DesignSystemThemeRegistry;
  const serialize = context.window.DesignSystemThemeComposer.serialize;
  const reports = [];
  const themes = registry.themes.map(({ id }) => {
    const result = composer.compose(data.baseThemePresetMap[id]);
    reports.push({ id, fixes: result.fixes, contrast: context.window.DesignSystemThemeContrast.audit(result.tokens) });
    return serialize(id, result.tokens);
  }).join('\n\n');
  const themeCss = '/* Generated by scripts/build-themes.cjs. Edit the seven preset layers, then rebuild. */\n' + themes + '\n';
  const bundle = read('css/tokens.css') + '\n' + themeCss + '\n' + read('css/components.css');
  const assets = { css: bundle, selector: read('js/theme-selector.js'), registry,
    fonts: '@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Space+Mono:wght@400;700&display=swap");\n' };
  return {
    'wiki/THEME_PRESET_MAP.md': '# Seven-layer theme recipes\n\nGenerated by `scripts/build-themes.cjs` from the preset source. Do not edit this table directly.\n\n' +
      'Every default theme is composed from `css/tokens.css` foundations followed by Family + Hue, Scheme, Style, Typography, Scale, and Texture. Control contrast adjustments run after composition. Manual overrides are preserved and applied last.\n\n' +
      '| Theme | Family | Hue | Scheme | Style | Typography | Scale | Texture |\n|---|---|---|---|---|---|---|---|\n' +
      registry.themes.map(({ id }) => '| ' + [id, ...['family','hue','scheme','style','typography','scale','texture'].map((key) => data.baseThemePresetMap[id][key])].map((v) => '`' + v + '`').join(' | ') + ' |').join('\n') +
      '\n\nThe complete recipe is the identity; the previous selected theme never participates in composition. Some authored schemes deliberately supply a fixed palette. A hue change is therefore not guaranteed to recolor a palette supplied by a scheme. Choose a semantic scheme such as `standard` for fully family/hue-driven palettes. See `../_docs/PRODUCT.md` for the export contract and limitations.\n',
    'js/theme-foundations.js': '/* Generated from css/tokens.css. */\nwindow.DesignSystemThemeFoundations = ' + JSON.stringify(defaults, null, 2) + ';\n',
    'css/themes.css': themeCss,
    'js/theme-package-assets.js': '/* Generated package assets for offline Studio export. */\nwindow.DesignSystemThemePackageAssets = ' + JSON.stringify(assets) + ';\n',
    '_docs/data/theme-composition-audit.json': JSON.stringify(reports, null, 2) + '\n',
  };
}
function build(check = false) {
  for (const [file, content] of Object.entries(artifacts())) {
    const target = path.join(root, file);
    if (check) {
      if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) throw new Error('Generated file is stale: ' + file);
    } else fs.writeFileSync(target, content);
  }
  console.log(check ? 'Generated theme artifacts are current.' : 'Built 21 themes, foundation data, package assets, and contrast report.');
}
if (require.main === module) build(process.argv.includes('--check'));
module.exports = { loadModel, artifacts, build };
